<footer>
    <div id="footer_nav">
        <a href="index.php"><img src="images/the_optional_group_logo.png" alt="The Optional Group Logo"
                class="logo"></a>
        <!-- ChatGPT GenAI Image Prompt: Create an image for a company logo for It company called The Optional Group. It’s a company which supplies remote it support and environmental impact. The group colours are blues, greens, and shades-->
        <ul id="footer_links">
            <li><a href="index.php">Home</a></li>
            <li><a href="about.php">About</a></li>
            <li><a href="jobs.php">Jobs</a></li>
            <li><a href="apply.php">Apply</a></li>
        </ul>
    </div>
    <div id="footer_row">
        <a class="footer_link" href="https://nagooptional.atlassian.net/jira/software/projects/SCRUM/summary"
            target="_blank">Jira
            Project Link</a>
        <a class="footer_link" href="https://github.com/Optional-WebTechGroup/optionalGroup_part2"
            target="_blank">Github Repo Link</a>
    </div>
    <p id="copyright">&copy; Copyright 2025 | The Optional Group | All Rights Reserved</p>
</footer>